### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by gwin** [simpliko/wpadverts#116]
Notice: Trying to get property of non-object in /home/chirodrdan1/public_html/wp-content/plugins/wpadverts/includes/admin-post-type.php on line 484

Notice: Trying to get property of non-object in /home/chirodrdan1/public_html/wp-content/plugins/wpadverts-bp/wpadverts-bp.php on line 445

Notice: Trying to get property of non-object in /home/chirodrdan1/public_html/wp-content/plugins/wpadverts/addons/featured/featured.php on line 252

Notice: Trying to get property of non-object in /home/chirodrdan1/public_html/wp-content/plugins/wpadverts-mark-as-sold/includes/class-wpadverts-mas-admin.php on line 285

**Comment by razor2016** [comment]
Hi,

Can you please update this issue? While wp-debug is set to true, these notices appear in the appearances > menu. 

Thanks

Screenshot: 

![wpadverts](https://user-images.githubusercontent.com/20941700/77067951-f672e500-6a0f-11ea-9895-5109bd871ab6.PNG)

**Comment by gwin** [comment]
Hi,
an update that fixes this problem will be released next week.
