### ISSUE TITLE
Replication Bug Hunt

### ISSUE THREAD

**Issue by gwin** [simpliko/wpadverts#121]
WPAdverts seems to be having an issue with replicating the [adverts_add] page, unfortunately it is hard to track it down, as only few users experienced it and even fewer (as i am writing it only one user actually) were able to have it happen twice.

# The Temporary Fix

The temporary solution is to download and install the Replication Bug Fix plugin https://www.dropbox.com/s/4s55ejw2a0dfdsi/wpadverts-replication-bug.zip?dl=0, once you have it installed go to wp-admin / Tools / Replication Bug panel and in the form there enter:

Page Title: The title the replicated pages have
Page IDs: The ID of original replicated page (which should not be deleted)

Once the form is filled press "Delete Now" it will trash all the replicated pages, which you can then permanently delete from wp-admin / Pages / Trash panel. It will not hurt to do a backup before clicking "Delete Now".

It's not much but at least will help with removing the duplicated pages quickly.

# Your input is needed

If you are having this issue your input in this thread will be extremely valuable, please post in this thread the following information:

1. the WPAdverts extensions you are using (and their versions)
2. any information that will help with identifying how to replicate the replication bug (one lead i have is that it happens after customizing a [adverts_add] form using Custom Fields extension but so far i was not able to confirm that)
3. anything else you can think of that would be helpful

I will use the user feedback to do a cross-reference and hopefully narrow the issue to a single plugin or maybe even find a way to replicate (and fix) the problem. 

Thanks for your help!

**Comment by nmccainjr** [comment]
Deactivate Jetpack by Wordpress It stop replicating ad pages
Just added Cloudflare started it again

Norman

WPAdverts extensions:

Authors  1.2.0
Category Icons  1.0.0
Custom Fields  1.2.1
Fee Per Category  1.1.1
Google Analytics  1.0.1
Maps and Locations  1.4.1
Mark As Sold  1.0.2
PayPal Payments Standard  1.0.2
reCAPTCHA  1.0.0
Restricted Categories  1.0.1
Stripe Integration  1.1.1

**Comment by gwin** [comment]
Should be fixed in 1.5.0, i am closing this for now.
