### ISSUE TITLE
Request For Nigerian Naira (N) Currency Symbol

### ISSUE THREAD

**Issue by maxellam** [simpliko/wpadverts#123]
I wish to commend your developers for creating this plugin as it would enhance ecommerce. However, I discovered that it does not have the Nigerian Naira symbol. It would be of great benefit to add this symbol so that Nigerian web designers can and online sellers can choose this currency in displaying their products for sale. Nigeria with a huge population of over 200million is the world's fastest growing ecommerce hub.

**Comment by gwin** [comment]
Hi,
right now it is possible to register a new currency in WPAdverts by adding the code below in your theme functions.php file

    add_filter("adverts_currency_list", function($list) {
        $list[] = array(
            "code"=>"NGN", 
            "sign"=>"₦",     
            "label"=>"Nigerian naira"    
        );
        return $list;
    } );

In one of next releases when i will be updating the currencies list i will add Nigerian Niara to the default list, thanks for the feedback.
