### ISSUE TITLE
Problème avec les pages créées avec wpadverts

### ISSUE THREAD

**Issue by anybodyyy** [simpliko/wpadverts#126]
Bonjour, 
j'ai un problème, lorsque l'on ajoute une annonce sur le plug-in, le plug-in crée une page mais cette page n'utilise pas du tout le thème et il y a une déformation du coup, comment puis-je faire pour qu'il n'y ait pas la déformation sur toutes les pages crée par le plug-in? 
Merci de votre aide ! 
![Capture](https://user-images.githubusercontent.com/73604777/97465645-8b44a600-1942-11eb-95d7-7c95e5289455.JPG)
![Capture1](https://user-images.githubusercontent.com/73604777/97465649-8bdd3c80-1942-11eb-97a6-fc9d2bf4dcb1.JPG)

**Comment by gwin** [comment]
Hi,
you seem to have a site-specific issue or a conflict with the theme, the GitHub tracker is for general issues only, please resend your question (in English please!) via the contact form at https://wpadverts.com/contact/, and remember to include a link to the page where you are having this problem, thanks.

I am closing this thread.
