### ISSUE TITLE
Information list

### ISSUE THREAD

**Issue by ElishaOtieno** [simpliko/wpadverts#132]
Information list in the product submission form remains the same, free and fails to update

**Comment by gwin** [comment]
Hi,
i am not exactly sure what do you mean, can you share some more details?

Is it a [adverts_add] or [adverts_manage] or some other page? and do you have some additional plugins/snippets installed?

If you can share a link to the page where you are having this problem it would be helpful as well.

**Comment by ElishaOtieno** [comment]
Hi Greg
[adverts_add]
Post advert/s – Opinion Dog <https://www.opiniondog.com/adverts/add/>

Information list at the bottom remains one- Free. Only one radio button
even if I try to add it in the settings.

Thanks in advance

Elisha Otieno

**Comment by gwin** [comment]
Hi,
thanks for the link, but it seems that to see the form i need to be logged-in? 

Can you make the [adverts_add] available to anyone or maybe email me some user login/password via contact form here https://wpadverts.com/contact/?

**Comment by ElishaOtieno** [comment]
Hi Greg,
The login details are: username- admin, password-  KaribuOpinion21 (K and
P-uppercase)

In trust

Elisha

**Comment by gwin** [comment]
H,
thanks, in the settings you had 3 postings but two of them were for renewals (ie. can be used only in the [adverts_manage] panel to renew an Ad), I added one more pricing for posting new ads and it seems to be showing fine in the https://www.opiniondog.com/adverts/add/

BTW. Please either change a password to your admin account or edit the reply and remove as right now anyone who will visit this page will be able to access your site as an administrator.

**Comment by gwin** [comment]
H,
thanks, in the settings you had 3 postings but two of them were for renewals (ie. can be used only in the [adverts_manage] panel to renew an Ad), I added one more pricing for posting new ads and it seems to be showing fine in the https://www.opiniondog.com/adverts/add/

BTW. Please either change a password to your admin account or edit the reply and remove as right now anyone who will visit this page will be able to access your site as an administrator.

**Comment by ElishaOtieno** [comment]
Hi Greg,
Thanks  a great deal. Password changed.
Kindly let me know if allowed to consult with you on other issues beyond WP
Adverts.

Kind regards

Elisha Otieno

**Comment by ElishaOtieno** [comment]
Hi Everyone,
Opinion Dog has changed its theme to free marketing and advertising. You're
encouraged to use the opportunity by registering and uploading your
products and services for global exhibition.
Those who had registered earlier are encouraged to register afresh. It is a
totally fresh start.

Kind regards

Elisha Otieno

Director
