### ISSUE TITLE
Undefined variable: id

### ISSUE THREAD

**Issue by erikdemarco** [simpliko/wpadverts#141]
I got this error:

Undefined variable: id    wp-content/plugins/wpadverts/includes/functions.php:1440

If you look at this line:
https://github.com/simpliko/wpadverts/blob/951e501ddd7291e2658dd60315d58d3e9fced915/includes/functions.php#L1440

$id is not declared yet. thus giving the error

**Comment by gwin** [comment]
Thanks, it will be fixed in the 1.5.8 release.
