### ISSUE TITLE
Font style on blocks not working

### ISSUE THREAD

**Issue by swissino** [simpliko/wpadverts#159]
HI, after upgrading to v 2.0 and replacing the shortcodes with the blocks, font style and colours do not work well; forms and every text in new blocks are smaller than my theme options and can't change it.
When editing font style and colours in Classifieds List block, I see the good styles in backend, but in frontend the style remains "default" and font is very small.
This issue happens in every Ad related block (small font, no styles).
The new options "Default styles" works well on buttons and forms.
Any idea if this is a theme, wpadvert, or CSS problem or anything else?

**Comment by gwin** [comment]
Hi,
please re-send the question via the contact form at https://wpadverts.com/contact/ as this seems to be more of a problem on the site/theme rather than in the plugin itself.

It will be also helpful if you could include a link to a page where you are having this problem.
