### ISSUE TITLE
Two buttons can’t be translated

### ISSUE THREAD

**Issue by swissino** [simpliko/wpadverts#166]
Hello!
I just found out that in v.2.0 there are two buttons in add advert confirmation page that can’t be translated:
View Ads List  / Publish Another Ad

We translated them manually, but maybe it would be great to fix them in new update!

this is the source code:

blocks/publish/templates/publish-save.php (Row 34): <?php wpadverts_block_button( array( "text" => “Publish another Ad", "type" => "secondary", "action" => "submit" )); ?>
blocks/publish/templates/publish-save.php (Row 38): <?php wpadverts_block_button( array( "text" => "View ads list", "type" => "secondary", "action" => "submit" )); ?>
blocks/manage/templates/manage-list.php (Row 175):  <?php wpadverts_block_button( array( "text" => "View ads list", "type" => "secondary", "action" => "submit" )); ?>

**Comment by gwin** [comment]
Thanks for reporting.
