### ISSUE TITLE
Error on WP Adverts plugin with contact form addon

### ISSUE THREAD

**Issue by davide-febbraio** [simpliko/wpadverts#178]
Hi all,

on my website, I'va installed WP Advert plugin with addon contact form.

After update I receive this erro:

Warning: Undefined array key "action_class" in /home/mhd-01/www.mysite.it/htdocs/wp-content/plugins/wpadverts/addons/contact-form/contact-form.php on line 224,

Could you help me to resolve this probem.

thanks a lot
Best regards
Davide

**Comment by gwin** [comment]
Hi,
thanks for the report, this will be fixed in version 2.0.5 which should be available today.
