### ISSUE TITLE
Can't add any images at WP adverts

### ISSUE THREAD

**Issue by PapitoAE** [simpliko/wpadverts#18]
Hellow. I setup WP adverts. But I can't downloading any image, because doesn't work buttom "choose files"

**Comment by gwin** [comment]
Hi, what is an URL to your page with [adverts_add] shortcode? Most likely this is happening on your site because there is JavaScript error on site and it prevents WPAdverts file uploader scripts from loading properly.

**Comment by PapitoAE** [comment]
I changed url from russian to english, but it doesn' help. Maybe need default URL ? Or problem lies elsewhere ?

**Comment by gwin** [comment]
This does not have anything to do with URLs, the problem is most likely with some other plugin or theme on your site generating a JavaScript error.
