### ISSUE TITLE
Gallery Not Showing

### ISSUE THREAD

**Issue by texascorvetteassociation** [simpliko/wpadverts#48]
My gallery is not showing up in the classified ads any longer.  Not sure what update wiped it out, as I only get a few classified ads a month.  I'm a corvette club and the members list their cars with me, so not many corvettes go up for sale.  I listed one tonight and the images won't work.  It use to...   If I click inside the gallery the lightbox will open and I can click through the images... just the slide show portion and the thumbs are not viewable.  Two pathes to the ads are:
http://texas-corvette-association.com/resources/resource-for-sale/   for the public to view or
for members  http://texas-corvette-association.com/our-business/adverts/
Thanks for your advise...  I'm not a programmer... just their Wordpress webmaster but I do my best  :-)  Appreciate any help you can offer...

**Comment by gwin** [comment]
This seems to be just a CSS problem, please try going to wp-admin / Appeareance / Customize / Additional CSS panel and add there the code below

`
img.wpadverts-slide-img {
    position: initial !important;
}
`

It should fix the problem and display the images in gallery properly.

**Comment by texascorvetteassociation** [comment]
Worked great!... thanks much!

Webmaster (Terri Butler)
Texas Corvette Association
