### ISSUE TITLE
i18n issues

### ISSUE THREAD

**Issue by wpchannel** [simpliko/wpadverts#51]
Hi,

some strings are not correctly formatted. The text domain is missing for instance in Google Maps add-on on these lines:

`<a href="#" class="wpadverts-mal-action-link wpadverts-mal-advanced-toggle adverts-icon-pencil"><?php _e("Change") ?></a>
                <a href="#" class="wpadverts-mal-action-link wpadverts-mal-reset-toggle adverts-icon-ccw"><?php _e("Reset") ?></a>`

Thanks

**Comment by gwin** [comment]
This is a ticket for Maps and Locations extension and it will be fixed in next release.
