### ISSUE TITLE
widget counts off/bug

### ISSUE THREAD

**Issue by jnorell** [simpliko/wpadverts#60]
There seems to be a problem with the adverts counts shown in the widget when using multi-level categories with "Show post counts" and "Show multiple category levels" are enabled.  When multiple categories are set for an advert, it includes that single advert multiple times in the count.

Eg. say there are the following categories:

- level1
- level1 > level2a
- level1 > level2b
- level1 > level2c

And I have 4 adverts, set with the following categories:

1. level1
2. level1 > level2a
3. level1 > level2b  &  level1 > level2c
4. level1  &  level1 > level2c

I would expect the count for level1 to be 4, but in this example it will be 6.  It will incorrectly count 3. and 4. twice, since they both have 2 categories.

**Comment by gwin** [comment]
This can be considered a bug due to how calculations look like, however, this is how WordPress is calculating the "counts" for all taxonomies (including default categories and tags) and it is not really possible to easily change it i am afraid.

**Comment by jnorell** [comment]
Maybe just track "seen" post id's in the_loop as it processes them?  I can't look at it right now but effectively:

```
while (have_posts()) {
...
// update count of posts per category (untested/surely broken code here):
$category_counts{$post->category}{$post->ID}++;
...
}
...
# output
for ( keys($category_counts) as $cat ) {
  echo $cat . "(" . count( $category_counts{$cat} ) . ")";
}
```

**Comment by gwin** [comment]
I am not really planning to change how WordPress counts the items as it is easy to make a mistake there and the results will be further off then with the default counting and on top of that the custom counting will require additional processing power which will result in slower page loading.

If you would like to change how the items are counted either way then there is a filter for that

`
add_filter( "adverts_category_post_count", "my_adverts_category_post_count", 10, 2 );
function my_adverts_category_post_count( $count, $term ) {
    // re-count the items for $term here
    return $count;
}
`

**Comment by jnorell** [comment]
Ok, I got a chance to look at the code on this, and yes, please ignore that last suggestion.  :)

Here is a solution which counts correctly and using a single WP_Query().  The current solution requires multiple get_terms() (one for each child category underneath the current term).  I don't have a test site with thousands of posts to really do good benchmarks, but maybe you would, or if not, what's your gut feeling on performance here?  I'll use it in our own custom filter for now.

function my_adverts_category_post_count( $count, $term ) {
    $the_query = new WP_Query( array(
        'post_type' => 'advert',
        'tax_query' => array(
            array(
                'taxonomy' => 'advert_category',
                'field' => 'id',
                'terms' => $term->term_id,
            )
        )
    ) );
    $count = $the_query->found_posts;
    return $count;
}

Thanks
