### ISSUE TITLE
wpadverts currency 

### ISSUE THREAD

**Issue by moumouni02** [simpliko/wpadverts#74]
Hi
I'm using the divi theme with the advert plugin. The code to change the currency gives me errors (unexpected token and unexpected LBRACE). How can I fix that?
![capture](https://user-images.githubusercontent.com/42709623/48515038-b322c800-e857-11e8-86ef-c97d80da7b56.JPG)

**Comment by gwin** [comment]
If you are pasting the code into theme functions.php file do that without the `<?php` on line 27.
