### ISSUE TITLE
GDPR agree checkbox

### ISSUE THREAD

**Issue by Miro382** [simpliko/wpadverts#79]
Add option to show before adding new ad, checkbox with GDPR.

**Comment by gwin** [comment]
We are not really planning to add such option to the core as this is not applicable to all sites.

That being said you can install the GDPR compliance for WPAdverts snippet it will add the checkboxes to the [adverts_list].

The snippet you can find here https://github.com/simpliko/wpadverts-snippets/tree/master/gdpr-compliance-for-wpadverts

How to install it you can read here https://github.com/simpliko/wpadverts-snippets/
