### ISSUE TITLE
User unable to play video on single post with windows 10/chrome

### ISSUE THREAD

**Issue by saenz** [simpliko/wpadverts#81]
A user is having issues trying to play a video on the detail single page inside the slider. They get the video controls but nothing happens when they click the play button. No errors are shown on the chrome console. This is happening on windows 10 in chrome. But they can play the video on the backend.

**Comment by saenz** [comment]
I did a little more digging and the video plays everywhere except inside the slider on the single page. This includes the swipebox. I tried a webm format video and same thing. 

I also tried uncommenting out the custom video controls in class-gallery-helper.php and adverts-single.js so I could use the native video controls but those did not work either. I didn't get the normal hover over the play button and the controls were not responsive.

**Comment by gwin** [comment]
Can you paste a link to a page where you are having this problem i cannot seem to be able to replicate it?

**Comment by saenz** [comment]
https://www.sbacc.org/advert/lucy-7

It's the last entry in the slider. And I couldn't reproduce it directly myself either. I have a user that is having this problem.

Jeff

**Comment by gwin** [comment]
Thanks for the details i will try to replicate the issue somehow, but right now the video plays fine for me at the page you linked to and i cannot see any error message in the console as well.

I do not think that this is a problem with the video format if it would not be playable in the browser the preview would not show at all.

One additional question, can the user click on other controls in the player? Maybe it is just that some transparent div is shown over the player controls?

**Comment by saenz** [comment]
She was able to hover over the play icon and get the hand. So, it should be clickable. But nothing happened when she tried clicking the icon. And I did mess with the 'wpadverts-slide-with-shadow' div which is included just below the video element. I left it in but set z-index on it to -1 but she got the same results.

She can play the video on all the admin screens and from the media link. It's just the advert page with the issue.

There is an option in chrome where you can right click and show the native controls. I'll see if she's able to play this way.

**Comment by saenz** [comment]
She was able to play the video by clicking the native play button after showing the controls. Can I disable the custom controls?

**Comment by gwin** [comment]
Currently, this is not possible i am afraid but i will make an option or filter in next release which will make it possible to disable the custom controls.

Right now the way to do that is most likely what you did, that is:
1. in wp-admin / Appearance / Customize / Additional CSS panel add the code below

`
.wpadverts-player,
.wpadverts-slide-with-shadow {
    display: none !important;
}
`

2. open file wpadverts/includes/class-gallery-helper.php and on line about 178 add controls="true" attributed to the video tag.

**Comment by gwin** [comment]
Since version 1.3.0 it will be possible to disable custom controls in the videos uploaded to the gallery by adding the line below in your theme functions.php file or in a separate plugin

`
add_filter( "adverts_gallery_enable_custom_controls", "__return_false" );
`
