### ISSUE TITLE
Problemi con plug in

### ISSUE THREAD

**Issue by AresSolong** [simpliko/wpadverts#95]
mi è stato chiuso il post senza darmi la possibilità di rispondere, io HO UN PROFILO, PAGATO, PRO, ma il plug a pagamento e pagato, mi dice installato,  ma non si vede e non si può usare. 
Questo quello che avevo scritto: Sono su wordpress.org e ho un piano aggiornato per i professionisti. il plugin è installato correttamente, dice, ma come se non fosse presente.

**Comment by gwin** [comment]
In case of a problem on your site, post on the support forums or send a support request via the contact form at https://wpadverts.com/contanct/ the GitHub Issue tracker should not be used for support requests.

Also when posting a support request please use English, thanks.
